//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DualDeepL.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DualDeepL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ブルガリア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェコ語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デンマーク語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DA {
            get {
                return ResourceManager.GetString("DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドイツ語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ギリシャ語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EL {
            get {
                return ResourceManager.GetString("EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペイン語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エストニア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィンランド語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フランス語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハンガリー語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インドネシア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イタリア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JA {
            get {
                return ResourceManager.GetString("JA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   韓国語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KO {
            get {
                return ResourceManager.GetString("KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リトアニア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラトビア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノルウェー語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NB {
            get {
                return ResourceManager.GetString("NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オランダ語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポーランド語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポルトガル語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ルーマニア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロシア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スロバキア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スロベニア語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スウェーデン語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トルコ語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウクライナ語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UK {
            get {
                return ResourceManager.GetString("UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中国語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZH {
            get {
                return ResourceManager.GetString("ZH", resourceCulture);
            }
        }
    }
}
