//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DualDeepL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sk-proj-Xgpn2ezpEwiXe5cRHOloT3BlbkFJu6s8SO7dq4IBWTv9iGwd")]
        public string APIKey {
            get {
                return ((string)(this["APIKey"]));
            }
            set {
                this["APIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Instruct1 {
            get {
                return ((string)(this["Instruct1"]));
            }
            set {
                this["Instruct1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Instruct2 {
            get {
                return ((string)(this["Instruct2"]));
            }
            set {
                this["Instruct2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fd0a929f-4397-31fc-964c-934271821c36:fx")]
        public string DeepLKey {
            get {
                return ((string)(this["DeepLKey"]));
            }
            set {
                this["DeepLKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FirstLanguage {
            get {
                return ((int)(this["FirstLanguage"]));
            }
            set {
                this["FirstLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecondLanguage {
            get {
                return ((int)(this["SecondLanguage"]));
            }
            set {
                this["SecondLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OriginalLanguage {
            get {
                return ((int)(this["OriginalLanguage"]));
            }
            set {
                this["OriginalLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"マンガのキャラクターのセリフを翻訳したい。以下の文章を、可能な限り原文のニュアンスを踏まえて{source}から{target}へ翻訳してください。\r\nただし、" +
            "#固有名詞 に記載された特定用語・固有名詞は英語表記を優先し、示すとおりに訳してください。:\"")]
        public string Prompt {
            get {
                return ((string)(this["Prompt"]));
            }
            set {
                this["Prompt"] = value;
            }
        }
    }
}
